POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkxNTgyMjF9.kbctNYa1R4OEldj_STWd8KwzWlfmfg0V-tFrjye3IRs
Content-Type: application/json


###
GET http://localhost:3000/orders/1.json 

###
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkxNTgyMjF9.kbctNYa1R4OEldj_STWd8KwzWlfmfg0V-tFrjye3IRs


