@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Nzk0MDk4OTB9.K6heXwXuCUrVkGfCijfKt9QRVh8YEdRC16Y7fp-7ouA

POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/orders/1.json 
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}


