@jwt = 
@jwt_admin = 

GET http://localhost:3000/products/4.json

###
GET http://localhost:3000/products.json

###
GET http://localhost:3000/products.json?category=Electronics

###
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "name": "Hoodie",
  "price": 90,
  "image_url": "",
  "description": "White XL"
}

###
PATCH http://localhost:3000/products/3.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "name": "Cool Socks"
}

###
DELETE http://localhost:3000/products/2.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

###
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json
