POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Joe Doe",
  "email": "joedoe1@example.com",
  "password": "12345",
  "password_confirmation": "12345"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "janedoe@example.com",
  "password": "12345"
}